# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "make run"
  bin = "./build/app"
  delay = 1000 # ms
  exclude_dir = ["assets", "build", "docs", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]
